---
# file: .../ansible/roles/docker_host/tasks/main.yaml


- name: Install docker from Ubuntu repository
  package:
    name: docker.io
    state: installed
  become: true


- name: Start and enable Docker services
  service:
    name: docker
    state: started
    enabled: true
  become: true


- name: Install packages for using apt over HTTPS
  package:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
  become: true
  tags: never, disabled
